baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "islu's Blog"
theme = "PaperMod"

[params]
showReadingTime = true
# showShareButtons = true
showToc = true
showBreadCrumbs = true
# showPostNavLinks = true
showCodeCopyButtons = true
comments = true

# Home Info
[params.homeInfoParams]
title = "Note everything"
content = "Developer, ..."

[[params.socialIcons]]
name = "github"
url = "https://github.com/islu"

# Menu
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30
