baseURL = 'https://islu.github.io/blog/'
languageCode = "zh-tw"
title = "islu's Blog"
theme = "PaperMod"

# defaultContentLanguage = "zh-tw"
# defaultContentLanguageInSubdir = false

[params]
showReadingTime = true
# showShareButtons = true
showToc = true
# showBreadCrumbs = true
showPostNavLinks = true
showCodeCopyButtons = true
comments = true

# Home Info
[params.homeInfoParams]
title = "Note everything"
content = "Developer, ..."

[[params.socialIcons]]
name = "github"
url = "https://github.com/islu"

# favicon
[params.assets]
favicon = "/blog/favicon/favicon.ico"
favicon16x16 = "/blog/favicon/favicon-16x16.png"
favicon32x32 = "/blog/favicon/favicon-32x32.png"
apple_touch_icon = "/blog/favicon/apple-touch-icon.png"
safari_pinned_tab = "/blog/favicon/safari-pinned-tab.svg"

# Menu
[[menu.main]]
identifier = "categories"
name = "🗂️ Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "🏷️ Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "📦 Archives"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "search"
name = "🔍 Search"
url = "/search/"
weight = 40

[outputs]
home = [ "HTML", "RSS", "JSON" ]

# [languages]

# [languages.zh-tw]
# contentDir = 'content/zh-tw'
# languageName = '中文'
# weight = 10

# [languages.en]
# contentDir = 'content/en'
# languageName = 'English'
# weight = 20

# [[languages.en.menu.main]]
# identifier = "categories"
# name = "🗂️ Categories"
# url = "/en/categories/"
# weight = 10

# [[languages.en.menu.main]]
# identifier = "tags"
# name = "🏷️ Tags"
# url = "/tags/"
# weight = 20

# [[languages.en.menu.main]]
# identifier = "archives"
# name = "📦 Archives"
# url = "/archives/"
# weight = 30

# [[languages.en.menu.main]]
# identifier = "search"
# name = "🔍 Search"
# url = "/search/"
# weight = 40